### ISSUE TITLE
Sample app doesn't compile

### ISSUE THREAD

**Issue by magnett** [checkout/CheckoutCardManagement-iOS#21]
Hi.
I am unable to compile and run the application, there are several errors.
Maybe because one of your packages (NetworkingClient-iOS) lives on a private repo(!) 
![SCR-20240221-m04](https://github.com/checkout/CheckoutCardManagement-iOS/assets/1730803/e92cb638-e2b4-42bb-a98a-20b23dcee9c0)

**Comment by okhan-okbay-cko** [comment]
Hey @magnett,

No, NetworkClient (a.k.a. CheckoutNetwork) lives [here](https://github.com/checkout/NetworkClient-iOS).

Are you able to run it on the simulator?

**Comment by magnett** [comment]
That NetworkingClient is a package of the sample app which doesn't work, ir requests an SSH key to your repo
![SCR-20240221-mis](https://github.com/checkout/CheckoutCardManagement-iOS/assets/1730803/dc763665-5a54-409b-bbf0-9c8f75bdd2d5)

**Comment by okhan-okbay-cko** [comment]
It's a public repo and shouldn't read any specific connection.

It doesn't request an SSH key to access to our repo but an SSH key to access to GitHub from your computer.

If you'd rather want to use another way of accessing it (e.g. HTTPS), try changing the cloning method under `Project` -> `Package Dependencies`. Or create an SSH key in your computer for general purpose following this guide [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent).

**Comment by okhan-okbay-cko** [comment]
Closing this issue by considering that it's resolved. Please feel free to re-open or to create a new one 👍
